# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object-segmentation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='object-segmentation.proto',
  package='godeye_service.object_segmentation',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19object-segmentation.proto\x12\"godeye_service.object_segmentation\"H\n\x0eSegmentRequest\x12\x36\n\x03img\x18\x01 \x01(\x0b\x32).godeye_service.object_segmentation.Image\"K\n\x0fSegmentResponse\x12\x38\n\x06\x62\x62oxes\x18\x01 \x03(\x0b\x32(.godeye_service.object_segmentation.Bbox\"\x18\n\x05Image\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x94\x01\n\x04\x42\x62ox\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04ymin\x18\x02 \x01(\x02\x12\x0c\n\x04xmax\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\x12\x0c\n\x04\x63onf\x18\x05 \x01(\x02\x12\r\n\x05label\x18\x06 \x01(\t\x12\x37\n\x04mask\x18\x07 \x01(\x0b\x32).godeye_service.object_segmentation.Image2\x8b\x01\n\x0cSegmentation\x12{\n\x0eSegmentObjects\x12\x32.godeye_service.object_segmentation.SegmentRequest\x1a\x33.godeye_service.object_segmentation.SegmentResponse\"\x00\x62\x06proto3'
)




_SEGMENTREQUEST = _descriptor.Descriptor(
  name='SegmentRequest',
  full_name='godeye_service.object_segmentation.SegmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='godeye_service.object_segmentation.SegmentRequest.img', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=137,
)


_SEGMENTRESPONSE = _descriptor.Descriptor(
  name='SegmentResponse',
  full_name='godeye_service.object_segmentation.SegmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bboxes', full_name='godeye_service.object_segmentation.SegmentResponse.bboxes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=214,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='godeye_service.object_segmentation.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='godeye_service.object_segmentation.Image.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=240,
)


_BBOX = _descriptor.Descriptor(
  name='Bbox',
  full_name='godeye_service.object_segmentation.Bbox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xmin', full_name='godeye_service.object_segmentation.Bbox.xmin', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ymin', full_name='godeye_service.object_segmentation.Bbox.ymin', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xmax', full_name='godeye_service.object_segmentation.Bbox.xmax', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ymax', full_name='godeye_service.object_segmentation.Bbox.ymax', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conf', full_name='godeye_service.object_segmentation.Bbox.conf', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='godeye_service.object_segmentation.Bbox.label', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask', full_name='godeye_service.object_segmentation.Bbox.mask', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=391,
)

_SEGMENTREQUEST.fields_by_name['img'].message_type = _IMAGE
_SEGMENTRESPONSE.fields_by_name['bboxes'].message_type = _BBOX
_BBOX.fields_by_name['mask'].message_type = _IMAGE
DESCRIPTOR.message_types_by_name['SegmentRequest'] = _SEGMENTREQUEST
DESCRIPTOR.message_types_by_name['SegmentResponse'] = _SEGMENTRESPONSE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Bbox'] = _BBOX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SegmentRequest = _reflection.GeneratedProtocolMessageType('SegmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTREQUEST,
  '__module__' : 'object_segmentation_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.object_segmentation.SegmentRequest)
  })
_sym_db.RegisterMessage(SegmentRequest)

SegmentResponse = _reflection.GeneratedProtocolMessageType('SegmentResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTRESPONSE,
  '__module__' : 'object_segmentation_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.object_segmentation.SegmentResponse)
  })
_sym_db.RegisterMessage(SegmentResponse)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'object_segmentation_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.object_segmentation.Image)
  })
_sym_db.RegisterMessage(Image)

Bbox = _reflection.GeneratedProtocolMessageType('Bbox', (_message.Message,), {
  'DESCRIPTOR' : _BBOX,
  '__module__' : 'object_segmentation_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.object_segmentation.Bbox)
  })
_sym_db.RegisterMessage(Bbox)



_SEGMENTATION = _descriptor.ServiceDescriptor(
  name='Segmentation',
  full_name='godeye_service.object_segmentation.Segmentation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=394,
  serialized_end=533,
  methods=[
  _descriptor.MethodDescriptor(
    name='SegmentObjects',
    full_name='godeye_service.object_segmentation.Segmentation.SegmentObjects',
    index=0,
    containing_service=None,
    input_type=_SEGMENTREQUEST,
    output_type=_SEGMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEGMENTATION)

DESCRIPTOR.services_by_name['Segmentation'] = _SEGMENTATION

# @@protoc_insertion_point(module_scope)
